version: '3'
services:

  localstack:
    image: localstack/localstack:0.11.4
    container_name: localstack
    ports:
      - "4566:4566"
    hostname: localstack
    environment:
      - EDGE_PORT=4566
      - SERVICES=dynamodb

  terraform:
    image: hashicorp/terraform:0.12.29
    depends_on:
      - localstack
    volumes:
      - ./terraform-localstack:/tmp/test/terraform
    working_dir: /opt/work
    entrypoint: sh
    command: >
      -c " cp -R /tmp/test/terraform/* /opt/work/ &&    terraform init && terraform apply -auto-approve -backup="-" -no-color &&  cp -R /opt/work/.terraform /opt/work/terraform.tfstate /tmp/test/terraform/ "

  backend_seed:
    build: ./backend-seed
    container_name: backend_seed
    restart: on-failure
    depends_on:
      - terraform
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=some-key
      - AWS_SECRET_ACCESS_KEY=some-secret
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://host.docker.internal:4566
